#!/bin/bash

case "$1" in
    'test-sw')
        for i in 8.2 8.3 8.4 8.5
        do
            PHP_VERSION=$i docker compose build 
            docker compose run --rm --remove-orphans app test-sw && docker compose down
        done
        ;;
    'update-vendor')
        docker compose run --rm --remove-orphans app update-vendor && docker compose down
        ;;
    'php-cs-fixer')
        docker compose run --rm --remove-orphans app php-cs-fixer && docker compose down
        ;;
    'rector')
        docker compose run --rm --remove-orphans app rector && docker compose down
        ;;
    'phpstan')
        docker compose run --rm --remove-orphans app phpstan && docker compose down
        ;;
    'sh')
        docker compose run --rm --remove-orphans app sh && docker compose down
        ;;
    *)
        echo "comands allowed"
        echo " - test-sw"
        echo " - update-vendor"
        echo " - php-cs-fixer"
        echo " - rector"
        echo " - phpstan"
        echo " - sh"
        exit 1
        ;;
esac


