services:
  app:
    build: 
        context: .
        args:
            PHP_VERSION: ${PHP_VERSION:-8.2}
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./vendor:/app/vendor
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./rector.php:/app/rector.php
      - ./phpstan.neon:/app/phpstan.neon
      - ./.php-cs-fixer.dist.php:/app/.php-cs-fixer.dist.php
    networks:
      - cache-multi-layer-network
    depends_on:
      redis-server:
        condition: service_healthy
      memcache-server:
        condition: service_healthy
  redis-server:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - cache-multi-layer-network
  memcache-server:
    image: memcached
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/localhost/11211'"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - cache-multi-layer-network
networks:
   cache-multi-layer-network:
    