name: Automazione del Rilascio (Al Merge PR)

on:
  pull_request:
    types:
      - closed
    branches:
      - main  # Si attiva solo per le PR che si uniscono al branch 'main'

jobs:
  release:
    # Esegue il job solo se la PR è stata *unita* (merged)
    if: github.event.pull_request.merged == true
    
    # Richiede i permessi di scrittura sul contenuto per poter creare tag, commit e release
    permissions:
      contents: write
      pull-requests: write 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del Codice
        uses: actions/checkout@v4
        with:
          # Fetch della cronologia completa per l'analisi dei commit
          # Per analizzare i commit della PR che sono stati uniti.
          fetch-depth: 0 
          
      - name: Configurazione Utente Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Esecuzione di Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          # Genera il changelog e determina il nuovo numero di versione
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-tag: true              # Crea un tag con la nuova versione
          output-file: CHANGELOG.md  # Aggiorna il file CHANGELOG.md
          skip-unstable: true        # Non rilascia versioni 'alpha', 'beta', ecc.
          
      - name: Verifica se è stata creata una nuova versione
        id: check_version
        run: echo "NEW_VERSION_TAG=${{ steps.changelog.outputs.tag }}" >> $GITHUB_ENV

      - name: Push del CHANGELOG e del Tag
        if: env.NEW_VERSION_TAG != '' # Esegue solo se una nuova versione è stata creata
        run: |
          # 1. Aggiunge i file aggiornati (es. CHANGELOG.md, file di versione)
          git add CHANGELOG.md
          # 2. Crea un commit (ignorato se non ci sono cambiamenti)
          git commit -m "chore(release): ${{ env.NEW_VERSION_TAG }}" || echo "Nessun cambiamento da committare"
          # 3. Invia il commit e il tag al repository
          git push
          git push origin ${{ env.NEW_VERSION_TAG }}

      - name: Crea GitHub Release
        if: env.NEW_VERSION_TAG != ''
        uses: softprops/action-gh-release@v1
        with:
          # Usa il corpo del changelog generato come note di rilascio
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.NEW_VERSION_TAG }} # Uso della variabile d'ambiente
          name: Release ${{ env.NEW_VERSION_TAG }}
          draft: false             # Pubblica immediatamente la release
          prerelease: false
